version: '3'

services:
  mongo:
    container_name: docker-mongo
    image: bitnami/mongodb:5.0
    ports:
      - '27017:27017'
      - '28017:28017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - ~/data/mongo:/data/db
